CRUD country
KSM-development/wst-backoffice pull request #10
Opened 2020-07-26 21:57 UTC by SerjiKSM

2020-07-27 05:47 UTC, Sabfir requested changes

2020-07-27 05:47 UTC, Sabfir commented on src/main/java/com/ksm/wstbackoffice/repository/CountryRepository.java
> +public interface CountryRepository extends JpaRepository<Country, Long> {
Did you tested it? The Id is Long

2020-07-27 10:09 UTC, SerjiKSM commented on src/main/java/com/ksm/wstbackoffice/repository/CountryRepository.java
> +public interface CountryRepository extends JpaRepository<Country, Long> {
done, fixed Long to String

2020-07-27 10:41 UTC, Sabfir commented on src/main/java/com/ksm/wstbackoffice/service/CountryService.java
> +    public List<Country> findAll() {
Please also add method find by Id

2020-07-27 11:32 UTC, SerjiKSM commented on src/main/java/com/ksm/wstbackoffice/service/CountryService.java
> +    public List<Country> findAll() {
added

2020-07-28 07:58 UTC, Sabfir approved these changes

2020-07-28 07:58 UTC, merged